# Selene Linter Configuration
std = "roblox"

[rules]
# Enforce best practices
unused_variable = "warn"
undefined_variable = "warn"
shadowing = "warn"
incorrect_standard_library_use = "warn"
global_usage = "warn"
